LIVE_MODEL = "gemini-3.1-flash-live-preview"

PRIMARY_LANGUAGE = "th-TH"
DEFAULT_VOICE = "Kore"

INPUT_SAMPLE_RATE = 16000
OUTPUT_SAMPLE_RATE = 24000

RESPONSE_MODALITIES = ["AUDIO"]

INPUT_TRANSCRIPTION_ENABLED = True
OUTPUT_TRANSCRIPTION_ENABLED = True
